query  GetPhones($pagination: Pagination, $sort: String, $first: Int) {
  getPhones(pagination: $pagination, sort: $sort, first: $first) {
    id
    name
    price
    image
    screen
    ram
    capacity
  }
}