query  GetPhones($first: Int, $pagination: Pagination, $sort: String) {
  getPhones(first: $first, pagination: $pagination, sort: $sort) {
    id
    phoneId
    name
    price
    fullPrice
    image
    screen
    ram
    capacity
  }
}